global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'zeroedc'
    static_configs:
      - targets: ['zeroedc-app:8000']  # internal service name

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
